# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build Node and deploy terraform
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1
  AWS_DEFAULT_OUTPUT: json
  PROJECT_NAME : mine-sweeper-5
  CI: false
  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  TFbuild:
    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: true
        
    - uses: hashicorp/setup-terraform@v2
    
    - name: TF Init
      run: terraform init
      working-directory:  terraform

        
    - name: TF Plan
      working-directory:  terraform
      run: terraform plan
    
    - name: TF Apply
      working-directory:  terraform
      run: terraform apply  -auto-approve
      

  NodeBuild:
    needs: TFbuild
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: true

    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Insall
      working-directory: Website/mine-sweeper-v2
      run: npm ci

    - name: Build
      working-directory: Website/mine-sweeper-v2
      run: ng build --configuration=development

    - name: Upload files
      run:  aws s3 cp Website/Scheduler-web-app/dist s3://$PROJECT_NAME-site-assets/ --recursive
